---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ktqueue
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ktqueue
  labels:
    app: ktqueue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktqueue
  template:
    metadata:
      labels:
        app: ktqueue
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        #kubernetes.io/hostname: host_name_you_want
      serviceAccountName: ktqueue
      containers:
      - name: ktqueue
        image: ktqueue
        imagePullPolicy: IfNotPresent
        command: [ "python3", "/ktqueue/server.py" ]
        env:
        - name: KTQ_AUTH_REQUIRED
          value: '0'
        - name: KTQ_COOKIE_SECRET
          value: ''
        - name: KTQ_OAUTH2_PROVIDER
          value: github
        - name: KTQ_OAUTH2_CLIENT_ID
          value: ''
        - name: KTQ_OAUTH2_CLIENT_SECRET
          value: ''
        - name: KTQ_OAUTH2_CALLBACK
          value: ''
        volumeMounts:
        - name: cephfs
          mountPath: /mnt/cephfs
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          privileged: true
      volumes:
      - name: 'cephfs'
        hostPath:
          path: /mnt/cephfs
        # cephfs:
        #   monitors:
        #   - localhost:6789
        #   user: admin
        #   secretRef:
        #     name: ceph-secret
        #   readOnly: false

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: ktqueue
  name: ktqueue
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  # externalIPs:
  #   - ip_you_want_to_access_form_outside
  selector:
    app: ktqueue
---
apiVersion: v1
kind: Namespace
metadata:
  name: ktqueue
